<?php
// This file is part of the NexusAI plugin for Moodle.
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Subscribable iCalendar (.ics) feed of a course's events (CAL-07 / #377).
 *
 * Unlike CAL-06 (one-off download), this is an endpoint that Google
 * Calendar / Apple Calendar subscribe to and refresh on their own. That's why
 * it CANNOT rely on the Moodle session: authentication is an opaque per-student
 * token, stored as a user preference (`local_nexusai_calfeedtoken`) — no new
 * table. The student can revoke it by generating a new one.
 *
 * Query params:
 *   - token   (string) — student token (44 chars, generated by the external fn)
 *   - course  (int)    — course whose events are served
 *   - download (int)   — optional; 1 forces a download instead of a subscription (used by CAL-06)
 *
 * Security:
 *   - The token identifies the student. It's also verified that this student
 *     is enrolled in the requested course — so the URL doesn't expose events
 *     from courses they're not enrolled in.
 *   - GET only, read-only. No other students' data is listed.
 *
 * @package    local_nexusai
 * @copyright  2026 NexusAI Team — UCC
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

// No cookies or session: the feed is requested by Google's server, not the student's browser.
define('NO_MOODLE_COOKIES', true);
define('NO_DEBUG_DISPLAY', true);

require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/calendar/lib.php');

global $DB, $CFG;

$token    = optional_param('token', '', PARAM_ALPHANUMEXT);
$courseid = optional_param('course', 0, PARAM_INT);
$download = optional_param('download', 0, PARAM_INT);

if (strlen($token) < 32 || $courseid <= 0) {
    http_response_code(400);
    die(get_string('errorinvalidparams', 'local_nexusai'));
}

// Resolve the student by their token (user preference). There's no index on
// value, but the user_preferences table is small and the token has 256 bits
// of entropy.
$pref = $DB->get_record('user_preferences', [
    'name'  => 'local_nexusai_calfeedtoken',
    'value' => $token,
], '*', IGNORE_MULTIPLE);

if (!$pref) {
    http_response_code(404);
    die(get_string('errorfeednotfound', 'local_nexusai'));
}

$userid = (int) $pref->userid;

$course = $DB->get_record('course', ['id' => $courseid], '*', IGNORE_MISSING);
if (!$course) {
    http_response_code(404);
    die(get_string('errorcoursenotfound', 'local_nexusai'));
}

$context = context_course::instance($course->id);
if (!is_enrolled($context, $userid, '', true)) {
    http_response_code(403);
    die(get_string('errorusernotenrolled', 'local_nexusai'));
}
if (!\local_nexusai\local\course_guard::is_enabled((int) $course->id)) {
    http_response_code(403);
    die(get_string('coursedisabled', 'local_nexusai'));
}

// Event window: from a week ago (so a recently-past event doesn't suddenly
// disappear from the calendar) to 120 days ahead.
$timestart = time() - 7 * DAYSECS;
$timeend   = time() + 120 * DAYSECS;

// The student's groups in the course: this way the feed includes events
// targeted at their groups, but not ones for groups they don't belong to.
$usergroups = array_keys(groups_get_all_groups((int) $course->id, $userid));

// Passing $userid in the users array is needed so activity events (assignment
// and quiz due dates) get included — without it, only standalone "course"
// events come back, which are the minority.
$events = calendar_get_legacy_events(
    $timestart,
    $timeend,
    [$userid],
    $usergroups ?: false,
    [(int) $course->id]
);

// The function combines user/group/course with OR, so passing the user also
// pulls in events from the student's OTHER courses. Filter explicitly: a
// course's feed is ONLY that course's events.
$events = array_filter($events, static function ($e) use ($course) {
    return (int) $e->courseid === (int) $course->id;
});

// Defensive cap: the feed is a login-less endpoint, we don't want to serve
// giant responses if a course has hundreds of events.
if (count($events) > 200) {
    $events = array_slice($events, 0, 200);
}

$calname = format_string($course->shortname, true, ['context' => $context]) . ' — NexusAI';
$ics = local_nexusai_build_ics($events, $calname, $CFG->wwwroot);

header('Content-Type: text/calendar; charset=utf-8');
$disposition = $download ? 'attachment' : 'inline';
header('Content-Disposition: ' . $disposition . '; filename="course-' . (int) $course->id . '.ics"');
header('Cache-Control: max-age=1800, private');
echo $ics;
exit;

/**
 * Builds the VCALENDAR text (RFC 5545) from Moodle events.
 *
 * @param array  $events  Events from calendar_get_legacy_events().
 * @param string $calname Visible calendar name.
 * @param string $wwwroot Moodle base URL (for each event's link).
 * @return string
 */
function local_nexusai_build_ics(array $events, string $calname, string $wwwroot): string {
    $fold = static function (string $line): string {
        // RFC 5545: lines over 75 octets are folded with CRLF + a space.
        $out = '';
        while (strlen($line) > 73) {
            $out .= substr($line, 0, 73) . "\r\n ";
            $line = substr($line, 73);
        }
        return $out . $line;
    };
    $esc = static function (string $v): string {
        // Neutralizes line breaks (prevents injecting fake VEVENT lines)
        // and escapes RFC 5545 field separators.
        $v = str_replace(["\r\n", "\r", "\n"], ' ', trim($v));
        return str_replace(['\\', ',', ';'], ['\\\\', '\\,', '\\;'], $v);
    };
    $dt = static function (int $ts): string {
        return gmdate('Ymd\THis\Z', $ts);
    };

    $lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//NexusAI//Course Calendar Feed//ES',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        'X-WR-CALNAME:' . $esc($calname),
        'REFRESH-INTERVAL;VALUE=DURATION:PT12H',
        'X-PUBLISHED-TTL:PT12H',
    ];

    $now = $dt(time());
    foreach ($events as $event) {
        $start = (int) $event->timestart;
        $end   = $start + (int) ($event->timeduration ?? 0);
        $uid   = 'nexusai-' . (int) $event->id . '@' . parse_url($wwwroot, PHP_URL_HOST);

        $summary = $esc((string) $event->name);
        $descparts = [];
        if (!empty($event->modulename)) {
            $descparts[] = ucfirst((string) $event->modulename);
        }
        $link = '';
        if (!empty($event->modulename) && !empty($event->instance)) {
            // A module's link uses the course module id (cmid), not the
            // instance id. If it can't be resolved, the URL is omitted.
            $cm = get_coursemodule_from_instance(
                $event->modulename,
                (int) $event->instance,
                (int) $event->courseid,
                false,
                IGNORE_MISSING
            );
            if ($cm) {
                $link = $wwwroot . '/mod/' . $event->modulename . '/view.php?id=' . (int) $cm->id;
            }
        }

        $lines[] = 'BEGIN:VEVENT';
        $lines[] = $fold('UID:' . $uid);
        $lines[] = 'DTSTAMP:' . $now;
        $lines[] = 'DTSTART:' . $dt($start);
        if ($end > $start) {
            $lines[] = 'DTEND:' . $dt($end);
        }
        $lines[] = $fold('SUMMARY:' . $summary);
        if ($descparts) {
            $lines[] = $fold('DESCRIPTION:' . $esc(implode(' · ', $descparts)));
        }
        if ($link) {
            $lines[] = $fold('URL:' . $link);
        }
        $lines[] = 'END:VEVENT';
    }

    $lines[] = 'END:VCALENDAR';
    return implode("\r\n", $lines) . "\r\n";
}
